use std::collections::HashMap;
use std::sync::LazyLock;

use crate::database::FileType;

pub static EXTENSION_MAP: LazyLock<HashMap<&'static str, FileType>> = LazyLock::new(|| {
    HashMap::from([
        // Text: plain text, docs, config, source code
        ("txt", FileType::Text),
        ("md", FileType::Text),
        ("markdown", FileType::Text),
        ("rst", FileType::Text),
        ("csv", FileType::Text),
        ("tsv", FileType::Text),
        ("json", FileType::Text),
        ("toml", FileType::Text),
        ("yaml", FileType::Text),
        ("yml", FileType::Text),
        ("xml", FileType::Text),
        ("html", FileType::Text),
        ("htm", FileType::Text),
        ("css", FileType::Text),
        ("ini", FileType::Text),
        ("cfg", FileType::Text),
        ("conf", FileType::Text),
        ("log", FileType::Text),
        ("rs", FileType::Text),
        ("py", FileType::Text),
        ("js", FileType::Text),
        ("ts", FileType::Text),
        ("jsx", FileType::Text),
        ("tsx", FileType::Text),
        ("c", FileType::Text),
        ("h", FileType::Text),
        ("cpp", FileType::Text),
        ("hpp", FileType::Text),
        ("java", FileType::Text),
        ("go", FileType::Text),
        ("rb", FileType::Text),
        ("php", FileType::Text),
        ("sh", FileType::Text),
        ("bash", FileType::Text),
        ("zsh", FileType::Text),
        ("sql", FileType::Text),
        // Image
        ("png", FileType::Image),
        ("jpg", FileType::Image),
        ("jpeg", FileType::Image),
        ("gif", FileType::Image),
        ("bmp", FileType::Image),
        ("webp", FileType::Image),
        ("svg", FileType::Image),
        ("ico", FileType::Image),
        ("tiff", FileType::Image),
        ("tif", FileType::Image),
        // Binary
        ("exe", FileType::Binary),
        ("dll", FileType::Binary),
        ("so", FileType::Binary),
        ("dylib", FileType::Binary),
        ("bin", FileType::Binary),
        ("o", FileType::Binary),
        ("a", FileType::Binary),
        ("zip", FileType::Binary),
        ("tar", FileType::Binary),
        ("gz", FileType::Binary),
        ("7z", FileType::Binary),
        ("rar", FileType::Binary),
        ("sqlite", FileType::Binary),
        ("db", FileType::Binary),
        ("mp3", FileType::Binary),
        ("mp4", FileType::Binary),
        ("wav", FileType::Binary),
        ("mov", FileType::Binary),
    ])
});
